# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.IntegerField()),
                ('countProduct', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AutentificationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, verbose_name='User')),
                ('passw', models.CharField(max_length=20, verbose_name='Pass')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=200, verbose_name='Покупатель')),
                ('Basket_ip_id', models.CharField(max_length=50)),
                ('time_of_creation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CommentArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleAuthor', models.CharField(max_length=200, verbose_name='Автор')),
                ('articleComment', models.TextField(verbose_name='Текст комментария')),
            ],
            options={
                'db_table': 'commentArticle',
            },
        ),
        migrations.CreateModel(
            name='imageInArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='SiteName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('tryCategory', models.BooleanField()),
                ('articleTitle', models.CharField(max_length=200)),
                ('articleText', models.TextField()),
                ('articleTextPreview', models.TextField(max_length=50)),
                ('articleFindText', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagePathBegin', models.ImageField(blank=True, null=True, upload_to='image')),
                ('countComment', models.IntegerField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'siteName',
            },
        ),
        migrations.AddField(
            model_name='imageinarticle',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteVisit.SiteName'),
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteVisit.SiteName'),
        ),
        migrations.AddField(
            model_name='arrproduct',
            name='Basket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteVisit.Basket'),
        ),
    ]
