# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-19 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0003_sitename_prevrecl'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='prevImage',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='sitename',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitename',
            name='articleTextPreview',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
