# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-19 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0004_auto_20170519_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitename',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
