# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-14 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0005_auto_20170519_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='Basket_ip_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='clientName',
            field=models.CharField(max_length=200, null=True, verbose_name='Покупатель'),
        ),
    ]
