# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0006_auto_20170614_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Of_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
