# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0007_list_of_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategories', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='list_of_categories',
            name='categories_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='siteVisit.Categories'),
            preserve_default=False,
        ),
    ]
