# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0010_list_of_categories_id_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List_Of_Categories',
            new_name='ListOfCategories',
        ),
    ]
