# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0011_auto_20170616_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitename',
            name='countComment',
            field=models.IntegerField(null=True),
        ),
    ]
