# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0013_auto_20170616_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofcategories',
            name='Basket_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='siteVisit.Basket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listofcategories',
            name='Categories_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='siteVisit.SiteName'),
            preserve_default=False,
        ),
    ]
