# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0014_auto_20170616_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofcategories',
            name='Basket_id',
        ),
        migrations.RemoveField(
            model_name='listofcategories',
            name='Categories_id',
        ),
    ]
