# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0016_listofcategories_action_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofcategories',
            name='action_categories',
            field=models.BooleanField(),
        ),
    ]
