# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0017_auto_20170620_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofcategories',
            name='action_categories',
        ),
    ]
