# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0019_imageinarticle_imageurlarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
