# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0020_sitename_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='produktOrder',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='statusBasket',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='Basket_ip_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
