# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='articleAuthor',
            field=models.TextField(),
        ),
    ]
