# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0003_sitename_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='imagePath',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
