# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0004_sitename_imagepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitename',
            name='imagePath',
        ),
    ]
