# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0005_remove_sitename_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='imagePathBegin',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
