# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0006_sitename_imagepathbegin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='articleTextPreview',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
