# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0007_sitename_articletextpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentarticle',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='siteVisit.SiteName'),
            preserve_default=False,
        ),
    ]
