# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0010_auto_20170313_1902'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentarticle',
            table='commentArticle',
        ),
        migrations.AlterModelTable(
            name='sitename',
            table='siteName',
        ),
    ]
