# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0011_auto_20170313_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentarticle',
            old_name='article',
            new_name='article_id',
        ),
        migrations.AlterField(
            model_name='commentarticle',
            name='articleAuthor',
            field=models.TextField(verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='commentarticle',
            name='articleComment',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
    ]
