# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0012_auto_20170314_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='articleFindText',
            field=models.TextField(default='', verbose_name=''),
            preserve_default=False,
        ),
    ]
