# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0014_auto_20170322_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='category',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentarticle',
            name='articleAuthor',
            field=models.CharField(max_length=200, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='sitename',
            name='articleFindText',
            field=models.CharField(max_length=200),
        ),
    ]
