# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0015_auto_20170327_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200, verbose_name='Категория')),
            ],
            options={
                'db_table': 'categoryArticle',
            },
        ),
        migrations.AlterField(
            model_name='sitename',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='categoryarticle',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteVisit.SiteName'),
        ),
    ]
