# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0016_auto_20170327_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryarticle',
            name='categoryTitle',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitename',
            name='articleFindText',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
