# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0017_auto_20170327_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
