# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0018_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitename',
            name='category',
        ),
    ]
