# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0020_categoryarticle_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryarticle',
            name='author',
        ),
        migrations.RemoveField(
            model_name='categoryarticle',
            name='category_id',
        ),
        migrations.AddField(
            model_name='sitename',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='siteVisit.categoryArticle'),
            preserve_default=False,
        ),
    ]
