# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0021_auto_20170328_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitename',
            name='category',
        ),
    ]
