# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0022_remove_sitename_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryarticle',
            name='category_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='siteVisit.SiteName'),
            preserve_default=False,
        ),
    ]
