# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteVisit', '0023_categoryarticle_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryarticle',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='sitename',
            name='author',
        ),
        migrations.AddField(
            model_name='categoryarticle',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitename',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='siteVisit.categoryArticle'),
            preserve_default=False,
        ),
    ]
