# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0025_auto_20170328_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='category',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
