# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0026_sitename_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryarticle',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='categoryArticle',
        ),
    ]
