# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0028_remove_sitename_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
