# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0029_sitename_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='tryCategory',
            field=models.BooleanField(default=''),
            preserve_default=False,
        ),
    ]
