# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0034_auto_20170329_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageInArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='sitename',
            name='image',
        ),
        migrations.AddField(
            model_name='imageinarticle',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteVisit.SiteName'),
        ),
    ]
