# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0037_auto_20170330_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutentificationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, verbose_name='User')),
                ('passw', models.CharField(max_length=20, verbose_name='Pass')),
            ],
        ),
        migrations.AddField(
            model_name='sitename',
            name='countComment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageinarticle',
            name='imagePath',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='sitename',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitename',
            name='imagePathBegin',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
