# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0038_auto_20170411_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
