# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0039_sitename_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitename',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
