# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0040_auto_20170427_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitename',
            name='price',
            field=models.FloatField(),
        ),
    ]
