# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0043_auto_20170428_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrproduct',
            name='Basket_ip_id',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
