# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0044_arrproduct_basket_ip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrproduct',
            old_name='basket',
            new_name='Product',
        ),
        migrations.RemoveField(
            model_name='arrproduct',
            name='Basket_ip_id',
        ),
        migrations.AddField(
            model_name='basket',
            name='Basket_ip_id',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
