# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0046_remove_basket_basket_ip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='Basket_ip_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
