# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0047_basket_basket_ip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='time_of_creation',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
    ]
