# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0050_auto_20170504_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='time_of_creation',
            new_name='created_date',
        ),
    ]
