# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0051_auto_20170504_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='created_date',
        ),
    ]
