# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0055_basket_time_of_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrproduct',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='arrproduct',
            name='countProduct',
        ),
    ]
