# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0056_auto_20170504_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='Basket_ip_id',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='time_of_creation',
        ),
        migrations.AddField(
            model_name='arrproduct',
            name='Product',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrproduct',
            name='countProduct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
