# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0059_remove_basket_time_of_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitename',
            name='created_date',
        ),
    ]
