# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteVisit', '0064_auto_20170504_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='time_of_creation',
            field=models.CharField(max_length=50),
        ),
    ]
